[project]
name = "blog-generator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Mohamed Ahmed", email = "mohamed.ahmed353635@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "langchain>=1.4.3",
]

[project.scripts]
blog-generator = "blog_generator:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
